#!/bin/sh
# Copies the live Home Assistant setup into the repo. HA stays the source of
# truth, as in ai/domovoy: change things in the UI, pull, commit.
set -e
cd "$(dirname "$0")"
HOST=root@192.168.1.243
DIR=/srv/homeassistant/config

# YAML that HA and its UI editors write: automations, scripts, scenes,
# blueprints, plus scripts like eac.py. secrets.yaml stays on the server.
rsync -a --delete --prune-empty-dirs --exclude=secrets.yaml \
  --exclude='.*/' --exclude=deps/ --exclude=tts/ --exclude=__pycache__/ \
  --include='*/' --include='*.yaml' --include='*.py' --include='custom_components/**' --exclude='*' \
  "$HOST:$DIR/" config/

# Areas and entities live in .storage as JSON; render a readable summary.
ssh "$HOST" python3 - "$DIR" > home.yaml <<'PY'
import json, sys
s = lambda name: json.load(open(f"{sys.argv[1]}/.storage/{name}"))["data"]
areas = s("core.area_registry")["areas"]
devices = {d["id"]: d for d in s("core.device_registry")["devices"]}
q = json.dumps
print("# Generated by pull.sh from .storage, do not edit.\n\nareas:")
for a in areas:
    print(f"  - id: {q(a['id'])}\n    name: {q(a['name'])}")
print("\nentities:")
for e in sorted(s("core.entity_registry")["entities"], key=lambda e: e["entity_id"]):
    if e.get("disabled_by"):
        continue
    dev = devices.get(e.get("device_id")) or {}
    area = e.get("area_id") or dev.get("area_id")
    name = e.get("name") or e.get("original_name") or dev.get("name_by_user") or dev.get("name")
    print(f"  - id: {e['entity_id']}")
    if name:
        print(f"    name: {q(name)}")
    if area:
        print(f"    area: {area}")
PY
